service: auth-server
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
provider:
  name: aws
  runtime: nodejs12.x
  #lambdaHashingVersion: 20201221
  region: eu-west-2
  timeout: 60 # optional, in seconds, default is 6
# service wide environment variables
environment:
  CLIENT_ID: ${file(config.json):CLIENT_ID}
  CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
  PROJECT_ID: ${file(config.json):PROJECT_ID}
  CALENDAR_ID: ${file(config.json):CALENDAR_ID}

  functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
